# OpenAPI 契约（变更部分）
# 完整契约由 FastAPI 自动生成
# 此文件仅记录本功能涉及的 Schema 变更

openapi: 3.1.0
info:
  title: Spec Generator API - Chat Context 变更
  version: 1.1.0

components:
  schemas:
    ChatMessage:
      type: object
      required:
        - role
        - content
      properties:
        role:
          type: string
          enum: [user, assistant]
          description: 消息角色
        content:
          type: string
          minLength: 1
          description: 消息内容

    GenerationRequest:
      type: object
      required:
        - description
      properties:
        description:
          type: string
          minLength: 1
          description: 用户输入描述或消息
        stream:
          type: boolean
          default: true
          description: 是否流式输出
        mode:
          type: string
          enum: [generate, chat]
          default: generate
          description: 生成模式
        current_prd:
          type: string
          nullable: true
          description: 当前 PRD 内容（chat 模式必填）
        chat_history:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/ChatMessage'
          maxItems: 4
          description: 对话历史（最多 4 条消息，即 2 轮对话）
        session_id:
          type: string
          nullable: true
          description: 会话 ID

paths:
  /api/v1/generate:
    post:
      summary: 生成或对话
      description: |
        - generate 模式：从用户描述生成新 PRD
        - chat 模式：基于现有 PRD 进行对话，支持传递对话历史
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerationRequest'
      responses:
        '200':
          description: 流式响应（NDJSON）或完整响应
        '400':
          description: chat 模式下 current_prd 缺失
